export const PRODUCTS_FETCH_REQUEST = 'PRODUCTS_FETCH_REQUEST';
export const PRODUCTS_FETCH_SUCCESS = 'PRODUCTS_FETCH_SUCCESS';
export const PRODUCTS_FETCH_FAILURE = 'PRODUCTS_FETCH_FAILURE';
export const SET_SELECTED_PRODUCT   = 'SET_SELECTED_PRODUCT';

export const VOUCHER_FETCH_REQUEST  = 'VOUCHER_FETCH_REQUEST';
export const VOUCHER_FETCH_SUCCESS  = 'VOUCHER_FETCH_SUCCESS';
export const VOUCHER_FETCH_FAILURE  = 'VOUCHER_FETCH_FAILURE';

export const VOUCHER_USE_REQUEST    = 'VOUCHER_USE_REQUEST';
export const VOUCHER_USE_SUCCESS    = 'VOUCHER_USE_SUCCESS';
export const VOUCHER_USE_FAILURE    = 'VOUCHER_USE_FAILURE';

export const FLASH_SHOW_ERROR       = 'FLASH_SHOW_ERROR';
export const FLASH_SHOW_SUCCESS     = 'FLASH_SHOW_SUCCESS';
export const FLASH_SHOW_INFO        = 'FLASH_SHOW_INFO';
export const FLASH_SHOW_WARNING     = 'FLASH_SHOW_WARNING';
export const FLASH_DISMISS          = 'FLASH_DISMISS';
